video_player:
  ros__parameters:
    video_path: "/mnt/d/VW/fota/new1/unittest/data/office_video1.mp4"
    loop: true
    frame_rate: 10

feature_tracker:
  ros__parameters:
    topic_name: "video_frames"
    equalize: true              # 是否需要均衡化
