video_player:
  ros__parameters:
    # video_path:         "/mnt/d/VW/fota/new1/unittest/data/dji_mimo_20251006_165752_0_1759934768534_video.mp4"
    video_path:         "/mnt/d/Slam/phone-3d-reconstruction/data/office_video1.mp4"
    loop:               true
    frame_rate:         5

feature_tracker:
  ros__parameters:
    topic_name:         "video_frames"    # 订阅的话题名称
    equalize:           true              # 是否需要均衡化
    max_feature_count:  150
    min_feature_dist:   20
    publush_frequence:  20                # 10
    show_track:         true              # 是否显示光流跟踪点的图片

vins_estimator:
  ros__parameters:
    window_size:        10
